unique_name: Training2
object_type: model
label: Training2
dimensions:
  - Color
  - Style
  - Weight
  - Size
metrics:
  - unique_name: m_factinternetsales_salesamount_sum
  - unique_name: m_factinternetsales_taxamt_avg
  - unique_name: m_factinternetsales_salesamount_avg
  - unique_name: m_factinternetsales_taxamt_sum
  - unique_name: m_factinternetsales_orderquantity_sum
  - unique_name: m_factinternetsales_customerkey_dc
  - unique_name: m_factinternetsales_customerkey_dce
relationships:
  - unique_name: >-
      factinternetsales_orderdatekey_to_dim_date_day_dimension_dim_date_day_dimension
      Level
    from:
      dataset: factinternetsales
      join_columns:
        - orderdatekey
    to:
      dimension: dim_date_day_dimension
      level: dim_date_day_dimension Level
